import type { Template } from './types';
export const DEMO_TEMPLATES: Template[] = [
  {
    id: 'coastal',
    title: 'Coastal diary',
    category: 'Lifestyle',
    scene: 'A quiet coast, late afternoon daylight',
    outfit: 'Linen shirt, relaxed trousers',
    pose: 'Walking, candid side view',
    prompt: 'Casual phone photograph, natural light, everyday framing, soft detail.',
    format: '4:5',
    cover: '/demo/coast.jpg',
    enabled: true,
  },
  {
    id: 'city',
    title: 'After hours',
    category: 'Editorial',
    scene: 'Modern city street at blue hour',
    outfit: 'Dark tailored jacket',
    pose: 'Looking over one shoulder',
    prompt: 'Candid street photo, subtle city reflections, believable skin, no studio lighting.',
    format: '4:5',
    cover: '/demo/city.jpg',
    enabled: true,
  },
  {
    id: 'studio',
    title: 'Soft studio',
    category: 'Portrait',
    scene: 'Bright creative studio, window light',
    outfit: 'Simple white t-shirt',
    pose: 'Relaxed posture, gentle smile',
    prompt: 'Everyday unedited phone photograph, clean light, natural expression.',
    format: '1:1',
    cover: '/demo/interior.jpg',
    enabled: true,
  },
];
